UX update in garud

diff --git a/garud b/garud
--- a/garud
+++ b/garud
@@ -1,150 +1,215 @@
 #!/bin/bash
 #coded by R0X4R
 
-if [ -z "$1" ]
-  then
-    echo "Target domain not supplied"
-    echo "Usage : garud target.com filename"
-    exit 1
-fi
-
-if [ -z "$2" ]
-  then
-    echo "Output filename not supplied"
-    echo "Usage : garud target.com filename"
-    exit 1
-fi
-
-if [ -z "$3" ]
-  then
-    echo "Tool not supplied either use waybackurls or gau"
-    echo "Usage : garud target.com filename waybackurls or gau"
-    exit 1
-fi
-
 wget -q --spider http://google.com
 if [ $? -ne 0 ];then
     echo "Connect to internet before running this tool!"
     exit 1
 fi
 
-if [ ! -d "$2" ]; then
-        mkdir $2
+domain=
+file=
+
+while getopts ":d:f:" o; do
+    case "${o}" in
+        d)
+            domain=${OPTARG} ;;
+
+        f)
+            file=${OPTARG} ;;
+
+    esac
+done
+
+if [ -z "$domain" ]
+  then
+    echo "Target domain not supplied"
+    echo "Usage : garud target.com filename"
+    exit 1
 fi
 
-RED="\e[31m"
-BOLD="\e[1m"
-NORMAL="\e[0m"
-GREEN="\e[92m"
+if [ -z "$file" ]
+  then
+    echo "Output filename not supplied"
+    echo "Usage : garud target.com filename"
+    exit 1
+fi
 
-echo -e ${GREEN}"\n          .                                                      . "
-echo -e ${GREEN}"        .n                   .                 .                  n. "
-echo -e ${GREEN}"  .   .dP                  dP                   9b                 9b.    . "
-echo -e ${GREEN}" 4    qXb         .       dX                     Xb       .        dXp     t "
-echo -e ${GREEN}"dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb "
-echo -e ${GREEN}"9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP "
-echo -e ${GREEN}" 9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP "
-echo -e ${GREEN}"  v9XXXXXXXXXXXXXXXXXXXXXi-   -vOOO8b   d8OOOi-   -vXXXXXXXXXXXXXXXXXXXXXPi "
-echo -e ${GREEN}"    v9XXXXXXXXXXXPi v9XXi   DIE    v98v8Pi  HUMAN   vXXPi v9XXXXXXXXXXXPi "
-echo -e ${GREEN}"        -------       9X.          .db|db.          .XP       ------- "
-echo -e ${GREEN}"                        )b.  .dbo.dPivviv9b.odb.  .dX( "
-echo -e ${GREEN}"                      ,dXXXXXXXXXXXb     dXXXXXXXXXXXb. "
-echo -e ${GREEN}"                     dXXXXXXXXXXXPi   .   v9XXXXXXXXXXXb "
-echo -e ${GREEN}"                    dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb "
-echo -e ${GREEN}"                    9XXbi   vXXXXXb.dX|Xb.dXXXXXi   vdXXP "
-echo -e ${GREEN}"                     vi      9XXXXXX(   )XXXXXXP      vi "
-echo -e ${GREEN}"                              XXXX X.vvi.X XXXX "
-echo -e ${GREEN}"                              XP^Xivb   divX^XX "
-echo -e ${GREEN}"                              X. 9  v   i  P )X "
-echo -e ${GREEN}"                              vb  v       i  di "
-echo -e ${GREEN}"                               v             i "
+if [ ! -d "$file" ]; then
+        mkdir $file
+fi
 
-echo -e "${RED}\n                             █▀▀ ▄▀█ █▀█ █░█ █▀▄"
-echo -e "${RED}                             █▄█ █▀█ █▀▄ █▄█ █▄▀"
-echo -e "${NORMAL}${BOLD}\n                           coded by ${GREEN}R0X4R${NORMAL}${BOLD} with ${RED}<3"
-sleep 2
+cd $file/
 
-cd $2/
-echo -e "${NORMAL}${BOLD}\nStarting scan on ${RED}$1${NORMAL}${BOLD}... \n"
-sleep 2
+show_menus() {
+	clear
 
-echo -e "${NORMAL}Starting ${GREEN}Assetfinder${NORMAL} on $1..."
-assetfinder --subs-only $1 |sort -u > $2-assetfinder.txt
-sleep 2
+    echo -e ${GREEN}"\n          .                                                      . "
+    echo -e ${GREEN}"        .n                   .                 .                  n. "
+    echo -e ${GREEN}"  .   .dP                  dP                   9b                 9b.    . "
+    echo -e ${GREEN}" 4    qXb         .       dX                     Xb       .        dXp     t "
+    echo -e ${GREEN}"dX.    9Xb      .dXb    __                         __    dXb.     dXP     .Xb "
+    echo -e ${GREEN}"9XXb._       _.dXXXXb dXXXXbo.                 .odXXXXb dXXXXb._       _.dXXP "
+    echo -e ${GREEN}" 9XXXXXXXXXXXXXXXXXXXVXXXXXXXXOo.           .oOXXXXXXXXVXXXXXXXXXXXXXXXXXXXP "
+    echo -e ${GREEN}"  v9XXXXXXXXXXXXXXXXXXXXXi-   -vOOO8b   d8OOOi-   -vXXXXXXXXXXXXXXXXXXXXXPi "
+    echo -e ${GREEN}"    v9XXXXXXXXXXXPi v9XXi   DIE    v98v8Pi  HUMAN   vXXPi v9XXXXXXXXXXXPi "
+    echo -e ${GREEN}"        -------       9X.          .db|db.          .XP       ------- "
+    echo -e ${GREEN}"                        )b.  .dbo.dPivviv9b.odb.  .dX( "
+    echo -e ${GREEN}"                      ,dXXXXXXXXXXXb     dXXXXXXXXXXXb. "
+    echo -e ${GREEN}"                     dXXXXXXXXXXXPi   .   v9XXXXXXXXXXXb "
+    echo -e ${GREEN}"                    dXXXXXXXXXXXXb   d|b   dXXXXXXXXXXXXb "
+    echo -e ${GREEN}"                    9XXbi   vXXXXXb.dX|Xb.dXXXXXi   vdXXP "
+    echo -e ${GREEN}"                     vi      9XXXXXX(   )XXXXXXP      vi "
+    echo -e ${GREEN}"                              XXXX X.vvi.X XXXX "
+    echo -e ${GREEN}"                              XP^Xivb   divX^XX "
+    echo -e ${GREEN}"                              X. 9  v   i  P )X "
+    echo -e ${GREEN}"                              vb  v       i  di "
+    echo -e ${GREEN}"                               v             i "
 
-echo -e "${NORMAL}Starting ${GREEN}Sublist3r${NORMAL} on $1..."
-python3 ~/tools/Sublist3r/sublist3r.py -d $1 -o $2-sublister.txt > /dev/null
-sleep 2
+    echo -e "${RED}\n                             █▀▀ ▄▀█ █▀█ █░█ █▀▄"
+    echo -e "${RED}                             █▄█ █▀█ █▀▄ █▄█ █▄▀"
+    echo -e "${NORMAL}${BOLD}\n                           coded by ${GREEN}R0X4R${NORMAL}${BOLD} with ${RED}<3"
 
-echo -e "${NORMAL}Starting ${GREEN}SubFinder${NORMAL} on $1..."
-subfinder -silent -d $1 -o $2-subfinder.txt > /dev/null
-sleep 2
+    sleep 1
+    echo -e "${NORMAL}${BOLD}\n   Target:${NORMAL}${GREEN} $domain ${NORMAL}"
+    echo -e "${BOLD}   Output:${NORMAL}${GREEN} $file ${NORMAL} \n "
+    echo "   0. Install all the tools"
+    echo "   1. Subdomain Enumeration"
+    echo "   2. Get Titles"
+    echo "   3. Subdomain Takeover"
+    echo "   4. Waybackurls"
+    echo "   5. Gau"
+    echo "   6. Gf Patterns"
+    echo "   7. Full scan"
+    echo -e "   8. Exit \n"
+}
 
-echo -e "${BOLD}\nFiltering subdomains of ${RED}$1... \n ${NORMAL} "
-cat $2-sublister.txt $2-assetfinder.txt $2-subfinder.txt | grep -v "*" |sort -u > $2-finalsubdomains.txt
-sleep 2
+read_option(){
+	local choice
+	read -p "Enter choice [ 1 - 8] " choice
+	case $choice in
+    
+    0) run_tools ;;
+	1) run_subenum ;;
+	2) run_gettitle ;;
+	3) run_subtake ;;
+	4) run_wayback ;;
+	5) run_gau ;;
+	6) run_gf ;;
+    7) run_all ;;
+	8) exit 0;;
+	*) echo -e "${RED}Error...${NORMAL}" && sleep 2
+	esac
+}
 
-echo -e "${NORMAL}Starting ${GREEN}HTTPx${NORMAL} on all filtered subdomains..."
-cat $2-finalsubdomains.txt | sort -u | uniq -u | httpx -silent > $2-alive.txt
-sleep 2
+pause(){
+  read -p "Press [Enter] key to continue..." fackEnterKey
+}
+ 
+load_colors() {
+    RED="\e[31m"
+    BOLD="\e[1m"
+    NORMAL="\e[0m"
+    GREEN="\e[92m"
+    YELLOW="\e[93m"
+}
 
-echo -e "${NORMAL}Starting ${GREEN}Ping${NORMAL} on all filtered subdomains..."
-cat $2-finalsubdomains.txt | sed '/@/d' | sed '/<BR>/d' | sed '/\_/d'| sed '/*/d' > $2-filtered.txt
-cat $2-filtered.txt | while read ip; 
-	do
-ping -c1 -W2 $ip > /dev/null
-if [[ $? -eq 0 ]];
-    then
-        echo -e "${ip}" | tee -a $2-live.txt > /dev/null
+install_tools() {
+    git clone https://github.com/aboul3la/Sublist3r.git $HOME/tools/Sublist3r &> /dev/null
+    sudo pip3 install -r $HOME/tools/Sublist3r/requirements.txt &> /dev/null
+    echo "alias sublister='python3 $HOME/tools/Sublist3r/sublist3r.py'" >> ~/.bashrc
+    wget https://raw.githubusercontent.com/haccer/subjack/master/fingerprints.json $HOME/tools/ &> /dev/null
+    git clone https://github.com/Edu4rdSHL/findomain.git $HOME/tools/findomain &> /dev/null
+    cd $HOME/tools/findomain && cargo build --release && sudo cp $HOME/tools/findomain/target/release/findomain /usr/bin/
+    sudo rm -r $HOME/tools/findomain
+    apt-get install amass &> /dev/null
+    GO111MODULE=on go get -u -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder &> /dev/null
+    go get -u github.com/tomnomnom/waybackurls &> /dev/null
+    go get -u github.com/tomnomnom/gf &> /dev/null
+    echo 'source $GOPATH/src/github.com/tomnomnom/gf/gf-completion.bash' >> ~/.bashrc
+    mkdir ~/.gf
+    cp -r $GOPATH/src/github.com/tomnomnom/gf/examples ~/.gf
+    git clone https://github.com/1ndianl33t/Gf-Patterns &> /dev/null
+    mv ~/Gf-Patterns/*.json ~/.gf
+    GO111MODULE=on go get -u -v github.com/lc/gau &> /dev/null
+    go get -u -v github.com/lukasikic/subzy && go install -v github.com/lukasikic/subzy &> /dev/null
+    go get github.com/haccer/subjack &> /dev/null
+    go get -u github.com/tomnomnom/assetfinder &> /dev/null
+    GO111MODULE=auto go get -u -v github.com/projectdiscovery/httpx/cmd/httpx &> /dev/null
+    echo -e "${YELLOW}Finished installing tools ${NORMAL}\n"
+    pause
+}
 
-    else
-        echo -e "${ip}" | tee -a $2-dead.txt > /dev/null
-    fi
+run_subenum() {
+    assetfinder --subs-only $domain | sort -u > $file-assetfinder.txt
+    python3 ~/tools/Sublist3r/sublist3r.py -d $domain -o $file-sublister.txt &> /dev/null
+    subfinder -silent -d $domain -o $file-subfinder.txt > /dev/null
+    sleep 2
+    cat $file-sublister.txt $file-assetfinder.txt $file-subfinder.txt | grep -v "*" | sort -u | sed '/@/d' | sed '/<BR>/d' | sed '/\_/d'| sed '/*/d' > $file-finalsubdomains.txt
+    sleep 2
+    cat $file-finalsubdomains.txt | sort -u | uniq -u | httpx -silent > $file-alive.txt
+    echo -e "${YELLOW}Done. ${NORMAL}\n"
+    pause
+}
 
-	done > random.txt;.
-rm random.txt
-sleep 2
+run_gettitle() {
+    cat $file-alive.txt | get-title > $file-gettitle.txt
+    echo -e "${YELLOW}Done. ${NORMAL}\n"
+    pause
+}
 
-echo -e "${NORMAL}Starting ${GREEN}Get-titles${NORMAL} to collect all titles of all subdomains..."
-cat $2-alive.txt | get-title > $2-gettitle.txt
-sleep 2
+run_subtake() {
+    subjack -w $file-finalsubdomains.txt -t 20 -ssl -c ~/tools/fingerprints.json -o $file-subjack.txt
+    subzy -targets $file-finalsubdomains.txt -hide_fails --verify_ssl -concurrency 20 | sort -u > $file-subzy.txt
+    echo -e "${YELLOW}Done. ${NORMAL}\n"
+    pause
+}
 
-echo -e "${NORMAL}Starting ${GREEN}subdomain takeover${NORMAL} scan on $1..."
-subjack -w $2-finalsubdomains.txt -t 20 -ssl -c ~/tools/fingerprints.json -o $2-subjack.txt
-subzy -targets $2-finalsubdomains.txt -hide_fails --verify_ssl -concurrency 20 | sort -u > $2-subzy.txt
-sleep 2
+run_wayback() {
+    cat $file-finalsubdomains.txt | waybackurls > $file-params.txt
+    echo -e "${YELLOW}Done. ${NORMAL}\n"
+    pause
+}
 
-echo -e "${NORMAL}${BOLD}Starting ${GREEN}$3${NORMAL}${BOLD} param output on $1... ${NORMAL} "
-sleep 2
-cat $2-finalsubdomains.txt | $3 > $2-$3.txt
+run_gau() {
+    cat $file-finalsubdomains.txt | gau > $file-params.txt
+    echo -e "${YELLOW}Done. ${NORMAL}\n"
+    pause
+}
 
-echo -e "Starting ${GREEN}XSS${NORMAL} param filtering on $1... ${NORMAL} "
-sleep 2
-cat $2-$3.txt | gf xss > $2-xss.txt
+run_gf() {
+    cat $file-params.txt | gf xss > $file-xss.txt
+    sleep 2
+    cat $file-params.txt | gf ssrf > $file-ssrf.txt
+    sleep 2
+    cat $file-params.txt | gf ssti > $file-ssti.txt
+    sleep 2
+    cat $file-params.txt | gf redirect > $file-redirect.txt
+    sleep 2
+    cat $file-params.txt | gf sqli > $file-sqli.txt
+    sleep 2
+    cat $file-params.txt | gf lfi > $file-lfi.txt
+    sleep 2
+    cat $file-params.txt | gf rce > $file-rce.txt
+    echo -e "${YELLOW}Done. ${NORMAL}\n"
+    pause
+}
 
-echo -e "Starting ${GREEN}SSRF${NORMAL} param filtering on $1... ${NORMAL} "
-sleep 2
-cat $2-$3.txt | gf ssrf > $2-ssrf.txt
+run_all () {
+    run_gau
+    run_gettitle
+    run_gf
+    run_subenum
+    run_subtake
+    run_wayback
+    pause
+}
 
-echo -e "Starting ${GREEN}SSTI${NORMAL} param filtering on $1... ${NORMAL} "
-sleep 2
-cat $2-$3.txt | gf ssti > $2-ssti.txt
+trap '' SIGINT SIGQUIT SIGTSTP
 
-echo -e "Starting ${GREEN}REDIRECT${NORMAL} param filtering on $1... ${NORMAL} "
-sleep 2
-cat $2-$3.txt | gf redirect > $2-redirect.txt
-
-echo -e "Starting ${GREEN}SQLi${NORMAL} param filtering on $1... ${NORMAL} "
-sleep 2
-cat $2-$3.txt | gf sqli > $2-sqli.txt
-
-echo -e "Starting ${GREEN}LFI${NORMAL} param filtering on $1... ${NORMAL} "
-sleep 2
-cat $2-$3.txt | gf lfi > $2-lfi.txt
-
-echo -e "Starting ${GREEN}RCE${NORMAL} param filtering on $1... ${NORMAL} "
-sleep 2
-cat $2-$3.txt | gf rce > $2-rce.txt
-
-sleep 2
-echo -e "${BOLD}\nAll your outputs are save in ${GREEN}$2/ \n"
+while true
+do
+    load_colors
+    show_menus
+    read_option
+done
